# Site settings
title: Christopher Bourez's blog
email: christopher.bourezATgmail.com
description: > # this means to ignore newlines until "baseurl:"
  Disrupting SASU. Christopher Bourez
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopher5106.github.io" # the base hostname & protocol for your site
twitter_username: christopher5106
github_username:  christopher5106

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
